### PR TITLE
WIP: CI: Set up Travis.

### PR DESCRIPTION
**Pull request by vonglasow**
Address hoaproject/Central#36.

### CODE REVIEW

**Comment by Hywan** [comment]
ping?

**Comment by vonglasow** [comment]
@Hywan some trouble to reproduce the error I seen on travis-ci on my laptop. Can't know which package is missing for running this tests. If you have some idea ?

**Comment by Hywan** [comment]
@vonglasow Please, rebase on `master` and try again.

**Comment by Hywan** [comment]
What's the status of this PR :-)?

**Comment by vonglasow** [comment]
Need to find packages missing on travis-ci to fix tests.

**Comment by Grummfy** [comment]
@vonglasow I have added a docker on my own repository https://github.com/Grummfy/Ustring/tree/ci hope it will help

**Comment by vonglasow** [comment]
@grummfy yes I have seen that still working on it on local thanks for your help

**Comment by vonglasow** [comment]
@Pierozi you can try

**Comment by Pierozi** [comment]
@vonglasow yep, I try it yesterday, but face a weird issue with composer.
https://travis-ci.org/Pierozi/Ustring/jobs/306769418

**Comment by vonglasow** [comment]
Maybe related to https://github.com/travis-ci/travis-ci/issues/3616

**Comment by Pierozi** [comment]
@vonglasow no, I've rebuild intl so. but now I can't even make composer install with your original code.
Can't explain. I will try to do it from scratch.

**Comment by vonglasow** [comment]
close in favor of #45

**Pull request closed without merging**
